### ISSUE TITLE
Updated attr-accept raises error

### ISSUE THREAD

**Issue by amureki** [paramaggarwal/react-dropzone#82] opened 2015-10-21 12:58 UTC
Greetings.
With new version 1.0.2 of https://github.com/okonet/attr-accept file upload raises error: accept is not a function.

**Comment by okonet** [comment] 2015-10-21 13:02
That's strange. I've just tested it and it worked fine. Can you provide me with a bit more info?
Steps to reproduce? Which browser? What configuration are you passing on Dropzone component? Thanks.

**Comment by amureki** [comment] 2015-10-21 13:06
@okonet thanks for fast reply.

OS X, Chrome Version 46.0.2490.71 (64-bit)
Just added example from readme and tried to upload image file there: https://monosnap.com/file/iFw73PX7Ans3JZuFt8QnbqN4n2AJx3.png

packages.json includes:
"attr-accept": "~1.0.2",
"react-dropzone": "^2.2.2",

But if I npm install attr-accept@1.0.1 all goes well on same code.

**Comment by PCreations** [comment] 2015-10-21 15:42
Same here, I'm using Webpack to create a bundle and the "accept" module in the DropZone module is an empty object, maybe there is some kind of circular dependency somewhere ?

**Comment by PCreations** [comment] 2015-10-21 16:02
The problem is the webpack.config.file outputing to library "react-attr" so `require('attr-accept')` requires a module exporting a 'react-attr' module.

**Comment by PCreations** [comment] 2015-10-21 16:27
In version 1.0.2 of attr-accept, I have to explicitly get the 'react-attr' key. So the `require` statement need to be `var accept = require('attr-accept')['react-attr'];` instead of just `var accept = require('attr-accept');`.

**Comment by okonet** [comment] 2015-10-21 16:30
Oh thanks for investigating! I'll make a fix ASAP and will release a new version.

**Comment by okonet** [comment] 2015-10-21 18:12
Should be fixed in 2.2.3

**Closed by okonet** 2015-10-21 18:12 UTC
